### ISSUE TITLE
Challenge completed level: basic

### ISSUE THREAD

**Issue by djkwlab** [learn-javascript-courses/rejection#1]
Hi Eric,

Here is my interpretation of the challenge Rejection Game challange.
https://github.com/ddaawwiidd/rejection

Any advices for rookie coder?

Cheers
Dawid

**Comment by ericelliott** [comment]
Hi Dawid,

This is a great start. I really like the way you styled the page, made it look nice, and included a description.

Can you separate different concerns into their own functions?
1. Loading / saving
2. Updating the state
3. Taking an object representing the state and drawing to the screen

> Life is simpler when UI components are unaware of the network, business logic, or app state. Given same props, always render same data.
