### ISSUE TITLE
first crack at it...

### ISSUE THREAD

**Issue by codyloyd** [learn-javascript-courses/rejection#4]
here's a working implementation.. it's not too pretty, and it uses localStorage.

obviously this thing didn't need Redux, but I have to use a thing to really learn it.. and I'm learning Redux.

In case the UI isn't clear.. you can click the questions to change the "response"

https://github.com/codyloyd/loser

http://codyloyd.com/loser/

**Comment by ericelliott** [comment]
Nice work!

Take a look at ["10 Tips for Better Redux Architecture"](https://medium.com/javascript-scene/10-tips-for-better-redux-architecture-69250425af44). You might notice a couple ways to improve your reducer.

I noticed a small issue in your calculation logic:

```js
const calculateScore = (state) => {
  return state.reduce((score,q) => {
    if (q.response == 'N') {
      return score += 10;
    } else if (q.response == 'Y') {
      return score += 1;
    } 
    return score;
  },0)
}
```

The `+=` operator is a reassignment operator, but `score` in this context can't be reassigned. You should use the `+` operator, instead to make it more clear what's really going on.

## Auto-increment Ids Collide

Check out [cuid](http://usecuid.org/) for safe client-generated ids.

**Comment by codyloyd** [comment]
great.. thanks!

I'm going to finish going through the Abramov course (and maybe the second one) and read the article, then come back and refactor.
