### ISSUE TITLE
Mid Level Challenge Completed

### ISSUE THREAD

**Issue by thoragio** [learn-javascript-courses/rejection#6]
Code: https://github.com/thoragio/rejection2
Demo: https://rejection2-uozqvyieal.now.sh/

Working with Next.js and learning React along the way was already quite a challenge, so I did not create any unit tests for this one. Will do that in the next project.

Thanks for the suggestion to try out Next.js. I enjoyed working with it, and with React as well.

**Comment by ericelliott** [comment]
Nice work!

I like the UI.

On the topic of unit tests, it can be very hard to unit test apps that are too tightly coupled. In particular, unit tests tend to work best with pure functions:

1. Given the same input, always return the same output
2. No side-effects

Pure functions aren't only good to make unit testing easier though, they also help you decouple your business logic from side-effects like network access and drawing the UI. For that reason, I like to isolate my app's business logic from network, storage, and drawing concerns.

Take this function for example:

```js
  recalculateScoreTotal () {
    const userAsks = this.state.userAsks
    let scoreTotal = 0
    Object
      .keys(userAsks)
      .map(key => {
        if (userAsks[key].status === 'Accepted') {
          scoreTotal += 1
        } else if (userAsks[key].status === 'Rejected') {
          scoreTotal += 10
        }
        this.setState({
          scoreTotal
        })
        db.updateScoreTotal(this.state.uid, scoreTotal)
      })
  }
```

If you split the score calculation out, it becomes trivially easy to unit test:

```js
const getScore = asks => asks.reduce((
  score, { status }
) => {
  switch (status) {
    case 'Accepted': return score + 1;
    case 'Rejected': return score + 10;
    default: return score;
  }
}, 0);
```

Consider implementing your next project using the [Redux architecture](https://medium.com/javascript-scene/10-tips-for-better-redux-architecture-69250425af44) to isolate business logic from view updates and side-effects.

**Comment by thoragio** [comment]
@ericelliott Awesome! Thanks for the example. I see what you mean now, and I will definitely try to this going forward.

I am already planning to implement my next project using Redux.

Thanks again for all of your input. It's greatly appreciated!
