### ISSUE TITLE
Challenge completed: basic level

### ISSUE THREAD

**Issue by indiesquidge** [learn-javascript-courses/rejection#7]
Hey, @ericelliott, thanks for creating this rejection challenge :)

I had a lot of fun with my first iteration of this project and can't wait to hear your advice on how I can improve it.

Source code: https://github.com/indiesquidge/rejection/tree/basic-level

Production site: http://austinwood.me/rejection/

**Comment by ericelliott** [comment]
Good job!

I noticed that your solution is not modular and [doesn't use TDD](https://medium.com/javascript-scene/the-outrageous-cost-of-skipping-tdd-code-reviews-57887064c412). Solutions like that won't scale to large production apps.

On your next app, try branching out a bit:

* Use TDD
* Use [Next.js](https://github.com/zeit/next.js/) + [React](https://github.com/ericelliott/react-pure-component-starter) + [Redux](https://medium.com/javascript-scene/10-tips-for-better-redux-architecture-69250425af44)
