### ISSUE TITLE
Basic Level completed!

### ISSUE THREAD

**Issue by maxyzli** [learn-javascript-courses/rejection#8]
Finish basic level using Next.js + React + Redux with TDD.

- [Rejection App Demo](https://rejection-jvyplxzsdo.now.sh/)
- [Github Repo](https://github.com/LIYINGZHEN/rejection)

#### 1. [ducks pattern](https://github.com/erikras/ducks-modular-redux) 

Colocate constants, action creators, and selectors with reducer.

##### Use TDD: Write Tests First

- Direct reducer tests: Test that the reducer produces the expected default state.
- Action creator tests: Test each action creator by applying the reducer to the action using some predetermined state as a starting point.
- Selector tests: Tests the selectors to ensure that all expected properties are there, including computed properties with expected values.

#### 3. Feature-based file structures

- [How to use Redux on highly scalable javascript applications?](https://medium.com/@alexmngn/how-to-use-redux-on-highly-scalable-javascript-applications-4e4b8cb5ef38#.b8l08w4za)

#### 1. Constants naming principle

Duck pattern say that **MUST have action types in the form `npm-module-or-app/reducer/ACTION_TYPE`**

But I notice you use `const ADD_CHAT = 'CHAT::ADD_CHAT'`

Which pattern should I follow?

#### 2. Where is the `describe` come from?

```js
describe('chatReducer()', ({ test }) => {
  test('with no arguments', ({ same, end }) => {
    const msg = 'should return correct default state';

    const actual = reducer();
    const expected = createState();

    same(actual, expected, msg);
    end();
  });
});
```

### 3. Is this a correct way to load data from localStorage?

```js
componentDidMount() {
  const { dispatch } = this.props;
  const serializedState = localStorage.getItem('rejection/state');
  const state = JSON.parse(serializedState) || {};
  if (state.asks) state.asks.map(ask => dispatch(addAsk(ask)));
}
```

**Comment by maxyzli** [comment]
I notice my UI is very ugly compared to others 😂. I will try to improve that.

**Comment by thoragio** [comment]
To answer your second question:

`describe` is just a name applied to the `tape` testing library. You would import it like any other dependency:

`import describe from 'tape'`

Instead of:
```
test('CardPlayer', nest => {
  nest.test('...card-player', assert => {
    const msg = 'CardPlayer should render the card-player div.';
```

You write:
```
describe('CardPlayer', ({test}) => {
  test('...card-player', ({equal, end}) => {
    const msg = 'CardPlayer should render the card-player div.';
```

You're using ES6 destructuring this way so you can avoid having to write `assert.equal` and `assert.end` and instead just write `equal` and `end`.

It's a question of style and what you prefer.

**Comment by maxyzli** [comment]
@thoragio Thanks. I decided to use firebase and material design for the mid-level challenge.

**Comment by ericelliott** [comment]
1. Constant strings don't matter much as long as:
    1. They're easy to read and identify &
    2. They don't collide with similarly named stuff in other modules.

**Comment by ericelliott** [comment]
On 3, I use the `connect` utility from react-redux which provides `mapStateToProps()` and `mapDispatchToProps()` in smart components, which will connect the redux state to props that can flow to presentation components through props.

Then you can use whatever async API you like to load the state and then dispatch an action to the store after the state is loaded. Common choices include:

1. redux-saga
2. redux-thunk
3. vanilla-js (create your own solution)

I personally prefer redux-saga, but before you dive into that, you need to understand generators.

Option 3 is easiest to start with.

**Comment by ericelliott** [comment]
Next time I want to see tests for components, too. See [TDD in ES6 & React](https://ericelliottjs.com/premium-content/webcast-tdd-es6-react/). Ignore the bits about Enzyme -- it was still flaky last I checked. I use Cheerio, instead.

You don't get synthetic event tests that way, but I just use functional tests for that. See [Nightwatch.js](http://nightwatchjs.org/) for easy functional testing.
